CI Docker Build Image Scan .

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,3 +1,4 @@
+
 name: Docker Build, Scan & Push
 
 on:
@@ -28,7 +29,7 @@ jobs:
       # -----------------------------
       # Determine Component & Version
       # -----------------------------
-      - name: Determine Image Tag
+      - name: Determine Component & Version
         id: version
         shell: bash
         run: |
@@ -41,15 +42,16 @@ jobs:
             VERSION="${GITHUB_REF#refs/tags/frontend-v}"
 
           else
-            COMPONENT="all"
-            VERSION="${GITHUB_SHA}"
+            echo "ERROR: Only semantic version tags are allowed."
+            echo "Expected: backend-v1.0.2 or frontend-v1.0.2"
+            exit 1
           fi
 
           echo "component=${COMPONENT}" >> "$GITHUB_OUTPUT"
           echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
 
           echo "Component: ${COMPONENT}"
-          echo "Docker version: ${VERSION}"
+          echo "Semantic Version: ${VERSION}"
 
       # -----------------------------
       # Docker Buildx
@@ -62,7 +64,7 @@ jobs:
       # =========================================================
 
       - name: Build Backend Image
-        if: steps.version.outputs.component == 'backend' || steps.version.outputs.component == 'all'
+        if: steps.version.outputs.component == 'backend'
         run: |
           docker build \
             -t $BACKEND_IMAGE:${{ steps.version.outputs.version }} \
@@ -72,7 +74,7 @@ jobs:
       # Trivy Backend Scan
       # -----------------------------
       - name: Scan Backend Image
-        if: steps.version.outputs.component == 'backend' || steps.version.outputs.component == 'all'
+        if: steps.version.outputs.component == 'backend'
         continue-on-error: true
         uses: aquasecurity/trivy-action@master
         with:
@@ -88,7 +90,7 @@ jobs:
       # Upload Backend Trivy Report
       # -----------------------------
       - name: Upload Backend Trivy Report
-        if: always() && (steps.version.outputs.component == 'backend' || steps.version.outputs.component == 'all')
+        if: always() && steps.version.outputs.component == 'backend'
         uses: actions/upload-artifact@v4
         with:
           name: trivy-backend-report
@@ -100,7 +102,7 @@ jobs:
       # =========================================================
 
       - name: Build Frontend Image
-        if: steps.version.outputs.component == 'frontend' || steps.version.outputs.component == 'all'
+        if: steps.version.outputs.component == 'frontend'
         run: |
           docker build \
             -t $FRONTEND_IMAGE:${{ steps.version.outputs.version }} \
@@ -110,7 +112,7 @@ jobs:
       # Trivy Frontend Scan
       # -----------------------------
       - name: Scan Frontend Image
-        if: steps.version.outputs.component == 'frontend' || steps.version.outputs.component == 'all'
+        if: steps.version.outputs.component == 'frontend'
         continue-on-error: true
         uses: aquasecurity/trivy-action@master
         with:
@@ -126,7 +128,7 @@ jobs:
       # Upload Frontend Trivy Report
       # -----------------------------
       - name: Upload Frontend Trivy Report
-        if: always() && (steps.version.outputs.component == 'frontend' || steps.version.outputs.component == 'all')
+        if: always() && steps.version.outputs.component == 'frontend'
         uses: actions/upload-artifact@v4
         with:
           name: trivy-frontend-report
@@ -148,7 +150,7 @@ jobs:
       # =========================================================
 
       - name: Push Backend Image
-        if: steps.version.outputs.component == 'backend' || steps.version.outputs.component == 'all'
+        if: steps.version.outputs.component == 'backend'
         run: |
           docker push \
             $BACKEND_IMAGE:${{ steps.version.outputs.version }}
@@ -158,7 +160,7 @@ jobs:
       # =========================================================
 
       - name: Push Frontend Image
-        if: steps.version.outputs.component == 'frontend' || steps.version.outputs.component == 'all'
+        if: steps.version.outputs.component == 'frontend'
         run: |
           docker push \
             $FRONTEND_IMAGE:${{ steps.version.outputs.version }}
@@ -194,3 +196,4 @@ jobs:
         if: steps.version.outputs.component == 'frontend'
         run: |
           docker push $FRONTEND_IMAGE:latest
+
